version: '3.9'

x-restart-policy: &restart_policy
  restart: on-failure

services:
  messages-api:
    << : *restart_policy
    container_name: messages-api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "5000:5000"
    environment: 
        ASPNETCORE_ENVIRONMENT: Release
        MESSAGE_CONNECTIONSTRING: ${MESSAGE_CONNECTIONSTRING}
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aspnet/https:/https:ro