x-restart-policy: &restart_policy
  restart: always

services:
  messages-api:
    << : *restart_policy
    container_name: messages-api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    ports:
      - "8000:80"
    environment: 
        ASPNETCORE_ENVIRONMENT: Release
    env_file: .env
    volumes: 
      - /var/logs/messages-api:/var/logs/messages-bot
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aspnet/https:/https:ro
